--- 
title: "Little Kids, Big Trips in East Tennessee"
author: "Katie Rosenberg and Joshua Rosenberg"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a book for parents and caretakers of children looking to take outdoors adventures in and around East Tennessee."
---


# Sections

## Introduction

### Why are we writing this book?

- We have been taking trips for around two years
- During the past year, due to COVID, outdoor trips were the main thing we did with our child
- We have done a lot of research, but we are only writing about places we have visited, hiked, paddled, and camped at with our little one

### Why this region/area?

- Its location is really great ([see here](https://recreationlinks.org/wp-content/uploads/2019/03/Outdoor_RecMap-MapSide__2ndEdition_04jul2018.pdf))
- It can be under-rated and hard to learn about

### Tips for getting started

### Trips

Parenthesess indicate places not-yet-visited.

## Trips 15 minutes or less away
- Ijams
- William Hastie
- Lakeshore
- Sharp's Ridge
- Concord Park

## Trips around 30 minutes away
- Cove Lake S.P.
- Norris Dam S.P.
- Big Ridge S.P.
- Seven Islands Birding S.P.
- House Mountain S.P.

## Trips around one hour away
- Frozen Head S.P.
- Obed Wild and Scenic River
- Big South Fork National River and Recreation Area (portions)
- Great Smoky Mountains National Park (portions)
- (Cumberland Gap National Historic Park) (portions)

## Trips more than one hour away but less than two hours away
- Great Smoky Mountains National Park (portions)
- Joyce Kilmer Memorial Forest
- Cherokee National Forest (portions)
- Pisgah National Forest (portions)
- (Nantahala National Forest) (portions)
- (Roan Mountain State Park)

## Further
- (Linville Gorge)
- (Mount Mitchell State Park)

# Format for each location

## Criteria for reviews
- accessibility
- beauty
- location and driving-related considerations (e.g., mountainous drive, dirt roads, remote location)
- ease of changing diapers
- accessibility/ease of use for different age groups
  - newborns (< 1 year old)
  - toddlers (1-3 years old)
  - young children (4-6 years old)
- playground/other areas for play

## Overview

A two paragraph minimum description of each location

## Map

- Overview
- For specific trails/activities

## Links/other information

- Links or other information

# Top three lists

- Best for infants
- Best for toddlers
- Best for young children

